name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Dockerhub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin docker.io
    - name: Build the package
      run: docker build -t maissacrement/devops-cli:latest .
    - name: Run
      run: docker run --name devops-cli -d maissacrement/devops-cli:latest
    - name: Exec cppcheck
      run: docker exec -i devops-cli /bin/sh -c "cd /app/src;cppcheck --enable=all --std=c++11 src --force"
    - name: Push to DockerHub
      run: docker push docker.io/maissacrement/devops-cli:latest
    - name: Clean
      run: |
        docker stop devops-cli
        docker rm -f devops-cli
